<a href="https://colab.research.google.com/github/tedeliott/multi_opti_for_GoldNPs/blob/main/research_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multi optimization for gold nanoparticles

## 1. Dataset

import raw dataset

In [2]:
import pandas as pd
import numpy as np

data = [
    # Sample_ID, inner_index, Date, HAuCl4_mM, PVP_mg_ml, AA_mM, Citrate_mM, pH,
    # Au_flow_rate, reducing_agent_flow_rate_mL_h, Z_Average_nm, PDI, Zeta_mV, note

    ["AuNP_001", "A", "28/04/2026", 1, 10, 20, 0,   3, 30, 30, 104.2, 0.1955, -5.321, ""],
    ["AuNP_002", "B", "28/04/2026", 1, 10, 20, 0,  11, 30, 30, 57.13, 0.4903, -6.766, ""],
    ["AuNP_003", "C", "28/04/2026", 1, 0,  20, 0,   3, 30, 30, 59.02, 0.2634, -21.56, ""],
    ["AuNP_004", "D", "28/04/2026", 1, 0,  20, 0,  11, 30, 30, 23.36, 0.4285, -12.39, ""],

    ["AuNP_005", "A", "07/05/2026", 1, 10, 20, 0,   3, 30, 30, 101.57, 0.1301, -7.395, "check fouling problem"],
    ["AuNP_006", "B", "07/05/2026", 1, 10, 20, 0,   3, 30, 30, 108.7, 0.1357, -6.304, "check fouling problem"],

    ["AuNP_007", "A", "22/05/2026", 1, 10, 20, 2,   3, 30, 30, 139.3, 0.3123, -10.279, "try tube type"],
    ["AuNP_008", "B", "22/05/2026", 1, 10, 20, 2,   3, 30, 30, 151.0, 0.3730, -10.045, "try tube type"],
    ["AuNP_009", "C", "22/05/2026", 1, 10, 20, 2,   3, 30, 30, 217.7, 0.8198, -10.1156, "try tube type"],
    ["AuNP_010", "D", "22/05/2026", 1, 10, 20, 2,   3, 30, 30, 171.9, 0.3971, -10.294, "try tube type"],

    ["AuNP_011", "A", "01/06/2026", 1, 10, 20, 2,  10, 30, 30, 67.163, 0.3107, -14.12, ""],
    ["AuNP_012", "B", "01/06/2026", 1, 10, 20, 0.2, 3, 30, 30, 108.9, 0.1441, -5.829, ""],
    ["AuNP_013", "C", "01/06/2026", 1, 10, 20, 0.2,10, 30, 30, 82.7, 0.3159, -7.157, ""],

    ["AuNP_014", "A", "04/06/2026", 1, 1,  20, 2,   3, 30, 30, 216.0, 0.4702, -7.775, ""],
    ["AuNP_015", "B", "04/06/2026", 1, 1,  20, 2,  10, 30, 30, 18.11, 0.6486, -6.88, ""],
    ["AuNP_016", "C", "04/06/2026", 1, 0,  20, 2,   3, 30, 30, np.nan, np.nan, np.nan, "very slow"],
    ["AuNP_017", "D", "04/06/2026", 1, 0,  20, 2,  10, 30, 30, np.nan, np.nan, np.nan, "very slow"],

    ["AuNP_018", "A", "08/06/2026", 1, 50, 20, 2,   3, 30, 30, 228.0, 0.0912, 1.9043, ""],
    ["AuNP_019", "B", "06/08/2026", 1, 50, 20, 2,  10, 30, 30, 113.6, 0.2568, -2.74, ""],

    ["AuNP_020", "A", "12/06/2026", 1, 30, 20, 2,   3, 30, 30, 143.4, 0.1677, -3.126, ""],
    ["AuNP_021", "B", "12/06/2026", 1, 30, 20, 2,  10, 30, 30, 30.09, 0.4766, -2.422, ""],
]

columns = [
    "Sample_ID",
    "inner_index",
    "Date",
    "HAuCl4_mM",
    "PVP_mg_ml",
    "AA_mM",
    "Citrate_mM",
    "pH",
    "Au_flow_rate",
    "reducing_agent_flow_rate_mL_h",
    "Z_Average_nm",
    "PDI",
    "Zeta_mV",
    "note"
]

df_raw = pd.DataFrame(data, columns=columns)

df_raw["Date"] = pd.to_datetime(df_raw["Date"], dayfirst=True)

df_raw

,Sample_ID,inner_index,Date,HAuCl4_mM,PVP_mg_ml,AA_mM,Citrate_mM,pH,Au_flow_rate,reducing_agent_flow_rate_mL_h,Z_Average_nm,PDI,Zeta_mV,note
0,AuNP_001,A,2026-04-28,1,10,20,0.0,3,30,30,104.200,0.1955,-5.3210,
1,AuNP_002,B,2026-04-28,1,10,20,0.0,11,30,30,57.130,0.4903,-6.7660,
2,AuNP_003,C,2026-04-28,1,0,20,0.0,3,30,30,59.020,0.2634,-21.5600,
3,AuNP_004,D,2026-04-28,1,0,20,0.0,11,30,30,23.360,0.4285,-12.3900,
4,AuNP_005,A,2026-05-07,1,10,20,0.0,3,30,30,101.570,0.1301,-7.3950,check fouling problem
5,AuNP_006,B,2026-05-07,1,10,20,0.0,3,30,30,108.700,0.1357,-6.3040,check fouling problem
6,AuNP_007,A,2026-05-22,1,10,20,2.0,3,30,30,139.300,0.3123,-10.2790,try tube type
7,AuNP_008,B,2026-05-22,1,10,20,2.0,3,30,30,151.000,0.3730,-10.0450,try tube type
8,AuNP_009,C,2026-05-22,1,10,20,2.0,3,30,30,217.700,0.8198,-10.1156,try tube type
9,AuNP_010,D,2026-05-22,1,10,20,2.0,3,30,30,171.900,0.3971,-10.2940,try tube type
10,AuNP_011,A,2026-06-01,1,10,20,2.0,10,30,30,67.163,0.3107,-14.1200,
11,AuNP_012,B,2026-06-01,1,10,20,0.2,3,30,30,108.900,0.1441,-5.8290,
12,AuNP_013,C,2026-06-01,1,10,20,0.2,10,30,30,82.700,0.3159,-7.1570,
13,AuNP_014,A,2026-06-04,1,1,20,2.0,3,30,30,216.000,0.4702,-7.7750,
14,AuNP_015,B,2026-06-04,1,1,20,2.0,10,30,30,18.110,0.6486,-6.8800,
15,AuNP_016,C,2026-06-04,1,0,20,2.0,3,30,30,NaN,NaN,NaN,very slow
16,AuNP_017,D,2026-06-04,1,0,20,2.0,10,30,30,NaN,NaN,NaN,very slow
17,AuNP_018,A,2026-06-08,1,50,20,2.0,3,30,30,228.000,0.0912,1.9043,
18,AuNP_019,B,2026-08-06,1,50,20,2.0,10,30,30,113.600,0.2568,-2.7400,
19,AuNP_020,A,2026-06-12,1,30,20,2.0,3,30,30,143.400,0.1677,-3.1260,
20,AuNP_021,B,2026-06-12,1,30,20,2.0,10,30,30,30.090,0.4766,-2.4220,

delete ineffective data(e.g. very slow data)

In [3]:
df_model = df_raw.dropna(subset=["Z_Average_nm", "PDI", "Zeta_mV"]).copy()

df_model

,Sample_ID,inner_index,Date,HAuCl4_mM,PVP_mg_ml,AA_mM,Citrate_mM,pH,Au_flow_rate,reducing_agent_flow_rate_mL_h,Z_Average_nm,PDI,Zeta_mV,note
0,AuNP_001,A,2026-04-28,1,10,20,0.0,3,30,30,104.200,0.1955,-5.3210,
1,AuNP_002,B,2026-04-28,1,10,20,0.0,11,30,30,57.130,0.4903,-6.7660,
2,AuNP_003,C,2026-04-28,1,0,20,0.0,3,30,30,59.020,0.2634,-21.5600,
3,AuNP_004,D,2026-04-28,1,0,20,0.0,11,30,30,23.360,0.4285,-12.3900,
4,AuNP_005,A,2026-05-07,1,10,20,0.0,3,30,30,101.570,0.1301,-7.3950,check fouling problem
5,AuNP_006,B,2026-05-07,1,10,20,0.0,3,30,30,108.700,0.1357,-6.3040,check fouling problem
6,AuNP_007,A,2026-05-22,1,10,20,2.0,3,30,30,139.300,0.3123,-10.2790,try tube type
7,AuNP_008,B,2026-05-22,1,10,20,2.0,3,30,30,151.000,0.3730,-10.0450,try tube type
8,AuNP_009,C,2026-05-22,1,10,20,2.0,3,30,30,217.700,0.8198,-10.1156,try tube type
9,AuNP_010,D,2026-05-22,1,10,20,2.0,3,30,30,171.900,0.3971,-10.2940,try tube type
10,AuNP_011,A,2026-06-01,1,10,20,2.0,10,30,30,67.163,0.3107,-14.1200,
11,AuNP_012,B,2026-06-01,1,10,20,0.2,3,30,30,108.900,0.1441,-5.8290,
12,AuNP_013,C,2026-06-01,1,10,20,0.2,10,30,30,82.700,0.3159,-7.1570,
13,AuNP_014,A,2026-06-04,1,1,20,2.0,3,30,30,216.000,0.4702,-7.7750,
14,AuNP_015,B,2026-06-04,1,1,20,2.0,10,30,30,18.110,0.6486,-6.8800,
17,AuNP_018,A,2026-06-08,1,50,20,2.0,3,30,30,228.000,0.0912,1.9043,
18,AuNP_019,B,2026-08-06,1,50,20,2.0,10,30,30,113.600,0.2568,-2.7400,
19,AuNP_020,A,2026-06-12,1,30,20,2.0,3,30,30,143.400,0.1677,-3.1260,
20,AuNP_021,B,2026-06-12,1,30,20,2.0,10,30,30,30.090,0.4766,-2.4220,

input variable X

In [5]:
input_cols = [
    "HAuCl4_mM",
    "PVP_mg_ml",
    "AA_mM",
    "Citrate_mM",
    "pH",
    "Au_flow_rate",
    "reducing_agent_flow_rate_mL_h"
]

X = df_model[input_cols].values

X

array([[ 1. , 10. , 20. ,  0. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  0. , 11. , 30. , 30. ],
       [ 1. ,  0. , 20. ,  0. ,  3. , 30. , 30. ],
       [ 1. ,  0. , 20. ,  0. , 11. , 30. , 30. ],
       [ 1. , 10. , 20. ,  0. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  0. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  2. , 10. , 30. , 30. ],
       [ 1. , 10. , 20. ,  0.2,  3. , 30. , 30. ],
       [ 1. , 10. , 20. ,  0.2, 10. , 30. , 30. ],
       [ 1. ,  1. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. ,  1. , 20. ,  2. , 10. , 30. , 30. ],
       [ 1. , 50. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 50. , 20. ,  2. , 10. , 30. , 30. ],
       [ 1. , 30. , 20. ,  2. ,  3. , 30. , 30. ],
       [ 1. , 30. , 20. ,  2. , 10. , 30. , 30. ]])

adjusting objectives

In [8]:
target_size = 50

df_model["size_error"] = abs(df_model["Z_Average_nm"] - target_size)
df_model["abs_zeta"] = abs(df_model["Zeta_mV"])

objective_cols = [
    "PDI",
     "abs_zeta",
   "size_error"
]

Y_objectives = df_model[objective_cols].values

Y_objectives

array([[1.95500e-01, 5.32100e+00, 5.42000e+01],
       [4.90300e-01, 6.76600e+00, 7.13000e+00],
       [2.63400e-01, 2.15600e+01, 9.02000e+00],
       [4.28500e-01, 1.23900e+01, 2.66400e+01],
       [1.30100e-01, 7.39500e+00, 5.15700e+01],
       [1.35700e-01, 6.30400e+00, 5.87000e+01],
       [3.12300e-01, 1.02790e+01, 8.93000e+01],
       [3.73000e-01, 1.00450e+01, 1.01000e+02],
       [8.19800e-01, 1.01156e+01, 1.67700e+02],
       [3.97100e-01, 1.02940e+01, 1.21900e+02],
       [3.10700e-01, 1.41200e+01, 1.71630e+01],
       [1.44100e-01, 5.82900e+00, 5.89000e+01],
       [3.15900e-01, 7.15700e+00, 3.27000e+01],
       [4.70200e-01, 7.77500e+00, 1.66000e+02],
       [6.48600e-01, 6.88000e+00, 3.18900e+01],
       [9.12000e-02, 1.90430e+00, 1.78000e+02],
       [2.56800e-01, 2.74000e+00, 6.36000e+01],
       [1.67700e-01, 3.12600e+00, 9.34000e+01],
       [4.76600e-01, 2.42200e+00, 1.99100e+01]])

## 2. Establish single scalarizing function with **Chimera**

In [4]:
pip install matter-chimera

Requirement already satisfied: matter-chimera in /usr/local/lib/python3.12/dist-packages (1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from matter-chimera) (2.0.2)

In [9]:
from chimera import Chimera

chimera = Chimera(
    tolerances=[0.2, 0.3, 0.1],
    absolutes=[False, False, False],
    goals=["min", "min", "max"]
)

y_chimera = chimera.scalarize(Y_objectives)

df_model["chimera_merit"] = y_chimera

df_model[[
    "Sample_ID",
    "PDI",
    "Z_Average_nm",
    "size_error",
    "Zeta_mV",
    "abs_zeta",
    "chimera_merit"
]]

,Sample_ID,PDI,Z_Average_nm,size_error,Zeta_mV,abs_zeta,chimera_merit
0,AuNP_001,0.1955,104.200,54.200,-5.3210,5.3210,0.371668
1,AuNP_002,0.4903,57.130,7.130,-6.7660,6.7660,0.686195
2,AuNP_003,0.2634,59.020,9.020,-21.5600,21.5600,0.470104
3,AuNP_004,0.4285,23.360,26.640,-12.3900,12.3900,0.627339
4,AuNP_005,0.1301,101.570,51.570,-7.3950,7.3950,0.444885
5,AuNP_006,0.1357,108.700,58.700,-6.3040,6.3040,0.406370
6,AuNP_007,0.3123,139.300,89.300,-10.2790,10.2790,0.516674
7,AuNP_008,0.3730,151.000,101.000,-10.0450,10.0450,0.574483
8,AuNP_009,0.8198,217.700,167.700,-10.1156,10.1156,1.000000
9,AuNP_010,0.3971,171.900,121.900,-10.2940,10.2940,0.597435
10,AuNP_011,0.3107,67.163,17.163,-14.1200,14.1200,0.515150
11,AuNP_012,0.1441,108.900,58.900,-5.8290,5.8290,0.389601
12,AuNP_013,0.3159,82.700,32.700,-7.1570,7.1570,0.520103
13,AuNP_014,0.4702,216.000,166.000,-7.7750,7.7750,0.667053
14,AuNP_015,0.6486,18.110,31.890,-6.8800,6.8800,0.836955
17,AuNP_018,0.0912,228.000,178.000,1.9043,1.9043,0.000000
18,AuNP_019,0.2568,113.600,63.600,-2.7400,2.7400,0.463818
19,AuNP_020,0.1677,143.400,93.400,-3.1260,3.1260,0.309200
20,AuNP_021,0.4766,30.090,19.910,-2.4220,2.4220,0.673148